name: company_prediction

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-dev nginx gunicorn uvicorn
        pip install virtualenv
        virtualenv myprojectenv
        source myprojectenv/bin/activate
        pip install fastapi uvicorn gunicorn

    - name: Test FastAPI server
      run: |
        gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app -b 0.0.0.0:8000 &
        sleep 3
        curl http://0.0.0.0:8000/docs/
        kill %1

    - name: Copy Nginx configuration
      run: |
        sudo cp myproject.nginx /etc/nginx/sites-available/
        sudo ln -s /etc/nginx/sites-available/myproject.nginx /etc/nginx/sites-enabled/

    - name: Test Nginx configuration
      run: sudo nginx -t

    - name: Reload Nginx
      run: sudo systemctl reload nginx

    - name: Upload code to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "./*"
        target: "./company_prediction"
        overwrite: true

    - name: SSH into EC2 and restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd company_prediction
          source myprojectenv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart company_prediction.service